config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/top' => 'homes#top'
  get 'homes/about' => 'homes#about'
  get 'homes/profile' => 'homes#profile'
  devise_for :admins,
             controllers: {
               sessions: 'admins/sessions',
               passwords: 'admins/passwords',
               registrations: 'admins/registrations'
             }
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations'
             }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admins/sessions#guest_admin'
  end
  namespace :admins do
    resources :contacts, only: %i[index edit update destroy]
  end
  get 'users/search' => 'searches#search'
  resources :contacts, only: %i[new create]
  resources :parts, only: %i[new create]
  resources :bigs, only: %i[show destroy]
  resources :muscles, only: %i[show update edit index destroy create] do
    resources :muscle_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
    resource :tags, only: [:index]
    get :following, on: :member
    get :workout, on: :member
  end
  get '/muscle/hashtag/:name', to: 'muscles#hashtag'

  resources :users, only: %i[show update edit] do
    resource :relationships, only: %i[create destroy]
    get :follows, on: :member
    get :followers, on: :member
    patch :withdraw, on: :member
    get :unsubscribe, on: :member
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def self.guest
    find_or_create_by!(email: 'guest_admin@example.com') do |user|
    user.password = SecureRandom.urlsafe_base64 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/big.rb
class Big < ApplicationRecord
  has_many :parts, dependent: :destroy
  has_many :users, through: :parts
  validates :name, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :muscle
end

app/models/muscle.rb
class Muscle < ApplicationRecord
  belongs_to :user
  belongs_to :part
  has_many :favorites, dependent: :destroy
  has_many :muscle_comments, dependent: :destroy
  has_many :muscle_tags, dependent: :destroy
  has_many :tags, through: :muscle_tags
  validates :weight, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :set_count, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :memo, presence: true
  validates :rep, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def belongs_to_current_user?(current_user)
    user == current_user
  end
  
  scope :perfect_work_tag_match, ->(work_tag) { where(work_tag:work_tag) }
  scope :backward_work_tag_match, ->(work_tag) { where('work_tag LIKE ?', "%#{work_tag}") }
  scope :forward_work_tag_match, ->(work_tag) { where('work_tag LIKE ?', "#{work_tag}%") }
  scope :partical_work_tag_match, ->(work_tag) { where('work_tag LIKE ?', "%#{work_tag}%") }
  after_create do
    # 1.controller側でcreateしたmuscleを取得
    muscle = Muscle.find_by(id: id)
    # 2.正規表現を用いて、muscleのwork_tag内から『#○○○』の文字列を検出
    tags = work_tag.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    # 3.mapメソッドでtags配列の要素一つ一つを取り出して、先頭の#を取り除いてDBへ保存する
    tags.uniq.map do |t|
      tag = Tag.find_or_create_by(tag_name: t.downcase.delete('#'))
      muscle.tags << tag
    end
  end
end

app/models/muscle_comment.rb
class MuscleComment < ApplicationRecord
  belongs_to :user
  belongs_to :muscle
  validates :comment, presence: true

  def belongs_to_current_user?(current_user)
  	user == current_user
  end
end

app/models/muscle_tag.rb
class MuscleTag < ApplicationRecord
  belongs_to :muscle
  belongs_to :tag
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :user
  belongs_to :big
  has_many :muscles, dependent: :destroy
  validates :name, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :muscle_tags, dependent: :destroy
  has_many :muscles, through: :muscle_tags
  validates :tag_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  has_many :muscles, dependent: :destroy
  has_many :parts, dependent: :destroy
  has_many :bigs, through: :parts
  has_many :favorites, dependent: :destroy
  has_many :muscle_comments, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: :following_id,
                                  dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: :follower_id,
                                   dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following
  has_many :contacts, dependent: :destroy
  validates :name, presence: true, length: { in: 2..20 }
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def belongs_to_current_user?(current_user)
    self == current_user
  end

  # user.rbに実装する
  scope :perfect_name_match, ->(name) { where(name: name) }
  scope :forward_name_match, ->(name) { where('name LIKE ?', "#{name}%") }
  scope :backward_name_match, ->(name) { where('name LIKE ?', "%#{name}") }
  scope :partical_name_match, ->(name) { where('name LIKE ?', "%#{name}%") }
  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: 'ゲスト') do |user|
    user.password = SecureRandom.urlsafe_base64 
    end
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :authenticate_user!
  def new
    @part = Part.new
    @bigs = Big.all
  end

  def create
    @part = Part.new(part_params)
    @part.user_id = current_user.id
    if @part.save
      redirect_to big_path(@part.big_id)
      flash[:notice] = "#{@part.name}を追加しました！！"
    elsif params[:part][:big_id] ==  '' && params[:part][:name] == ''
      redirect_to request.referer
      flash[:notice] = '部位と種目が入力されていません'
    elsif params[:part][:big_id] ==  ''
      redirect_to request.referer
      flash[:notice] = '部位が入力されていません'
    else
      @bigs = Big.all
      redirect_to request.referer
      flash[:notice] = '種目が入力されていません'
    end
  end

  private

  def part_params
    params.require(:part).permit(:name, :big_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bigs_helper.rb
module BigsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when 'alert'
      'warning'
    when 'notice'
      'success'
    when 'error'
      'danger'
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/muscles_helper.rb
module MusclesHelper
  def render_with_hashtags(work_tag)
    sanitize work_tag.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/) { |word| link_to word, "/muscle/hashtag/#{word.delete('#')}" }
    # gsubでハッシュタグ(/[#＃])と＃についてる文字(\w\p{Han}ぁ-ヶｦ-ﾟー]+/)をlink_to wordでリンクにして、sanitizeでhtml化している。
    # sanitizeを使う理由はXSS対策である。.html_safeだとrubocopにも怒られる
  end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/parts/_menu.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="about mt-5">
      <div class="about-text">
        <h2>トレーニングメニュー</h2>
        <p>
          筋肉を大きくする為には睡眠、食事、トレーニングの三代要素がありますが、<br>その中でも日々のトレーニングでどれだけ自分を追い込むかで成長速度が変わってきます。<br>
          ここではおすすめのトレーニングメニュー３選を紹介します。
        </p>
      </div>
    </div>
  </div>
  <section id="intro">
  <h2 class="intro-title pb-3">トレーニングメニュー３選</h2>
  <div class="row justify-content-center">
    <div class="intro-box">
      <div class="intro-row">
        <div class="intro-box-count">1.</div>
        <div class="intro-box-title"><span class="marker">胸重視</span></div>
      </div>
        <div class="intro-box-txt">
          月：胸＋腕（上腕三頭筋）<br>
          火：背中＋腕（上腕二頭筋）<br>
          水：休み<br>
          木：肩＋腕（上腕三頭筋）<br>
          金：脚＋腕（上腕二頭筋）<br>
          土：胸＋腕（上腕三頭筋）<br>
          日：休み
        </div>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="intro-box">
      <div class="intro-row">
        <div class="intro-box-count">2.</div>
        <div class="intro-box-title"><span class="marker">オススメ！</span></div>
      </div>
      月：胸＋ 肩(フロント）+ 腕（上腕三頭筋）<br>
      火：背中＋ 肩(リア）+ 腕（上腕二頭筋）<br>
      水：脚＋ 肩(サイド）<br>
      木：休み<br>
      金：胸＋ 肩(フロント）+ 腕（上腕三頭筋）<br>
      土：背中＋ 肩(リア）+ 腕（上腕二頭筋）<br>
      日：脚＋ 肩(サイド）<br>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="intro-box">
      <div class="intro-row">
        <div class="intro-box-count">3.</div>
        <div class="intro-box-title"><span class="marker">肩重視</span></div>
      </div>
      月：胸+腹筋<br>
      火：肩＋腕（上腕三頭筋）<br>
      水：背中＋腕（上腕二頭筋)<br>
      木：休み<br>
      金：脚＋腕（上腕二頭筋）<br>
      土：肩＋腕（上腕三頭筋）<br>
      日：休み
    </div>
  </div>
  </section>
</div>

app/views/parts/new.html.erb
<div class="row justify-content-center">
	<h3 class="intro-title pb-3">部位のリンクを押して本日のトレーニングを公開しましょう！</h4>
</div>
<div class="row justify-content-center">
	<div class="col-8 my3 border">
		<div class="row justify-content-center border-part">
		部位一覧)
			<% @bigs.each.with_index(1) do |big, index| %>
				<tr>
					<th><button type="button" class="btn btn-light"><%= index %></th>
					<td><%= link_to big.name, big_path(big.id) %></td></button>
				</tr>
			<% end %>
		</div>
		<div class="row justify-content-center">
			<h4 class="intro-title pb-3">部位を選んで種目を追加しましょう！</h4>
		</div>
		<div class="row justify-content-center mt-3">
			<%= form_with model: @part, local: true do |f| %>
			<div class="col">
			<%= f.label :name, "部位" %>
			<%= f.collection_select :big_id, Big.all, :id, :name, :include_blank => "選択してください" %>
			</div>
			<div class="col">
				<%= f.label :name, "種目" %>
				<%= f.text_area :name, placeholder: "例）懸垂"  %>
				<%= f.submit "種目を追加", class: "btn btn-danger" %>
			</div>
			<% end %>
		</div>
	</div>
	<%= render 'parts/menu' %>
</div>

app/views/parts/show.html.erb
<div class="row justify-content-center">
	<h1><%= @big.name %></h1>
</div>
<div class="row justify-content-center">
	<%= link_to 'TODAY WORKOUTに戻る', new_part_path %>
</div>
<div class="row justify-content-center">
	<table class="table table-bordered">
		<% @part.each do |part| %>
			<tr>
				<td><%= link_to "#{ part.name }",workout_muscle_path(part.id) %></td>
			</tr>
		<% end %>
	</table>
</div>