config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/top' => 'homes#top'
  get 'homes/about' => 'homes#about'
  get 'homes/profile' => 'homes#profile'
  devise_for :admins,
             controllers: {
               sessions: 'admins/sessions',
               passwords: 'admins/passwords',
               registrations: 'admins/registrations'
             }
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations'
             }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admins/sessions#guest_admin'
  end
  namespace :admins do
    resources :contacts, only: %i[index edit update destroy]
  end
  get 'users/search' => 'searches#search'
  resources :contacts, only: %i[new create]
  resources :parts, only: %i[new create]
  resources :bigs, only: %i[show destroy]
  resources :muscles, only: %i[show update edit index destroy create] do
    resources :muscle_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
    resource :tags, only: [:index]
    get :following, on: :member
    get :workout, on: :member
  end
  get '/muscle/hashtag/:name', to: 'muscles#hashtag'

  resources :users, only: %i[show update edit] do
    resource :relationships, only: %i[create destroy]
    get :follows, on: :member
    get :followers, on: :member
    patch :withdraw, on: :member
    get :unsubscribe, on: :member
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  has_many :muscles, dependent: :destroy
  has_many :parts, dependent: :destroy
  has_many :bigs, through: :parts
  has_many :favorites, dependent: :destroy
  has_many :muscle_comments, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: :following_id,
                                  dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: :follower_id,
                                   dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following
  has_many :contacts, dependent: :destroy
  validates :name, presence: true, length: { in: 2..20 }
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def belongs_to_current_user?(current_user)
    self == current_user
  end

  # user.rbに実装する
  scope :perfect_name_match, ->(name) { where(name: name) }
  scope :forward_name_match, ->(name) { where('name LIKE ?', "#{name}%") }
  scope :backward_name_match, ->(name) { where('name LIKE ?', "%#{name}") }
  scope :partical_name_match, ->(name) { where('name LIKE ?', "%#{name}%") }
  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: 'ゲスト') do |user|
    user.password = SecureRandom.urlsafe_base64 
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :check_guest, only: :destroy

  def after_sign_up_path_for(_resource)
    muscles_path
  end

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end

  def edit
    @guest_user = User.guest
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(_resource)
    muscles_path
  end

  def after_sign_out_path_for(_resource)
    root_path
  end

  def new_guest
    user = User.guest
    sign_in user
    redirect_to muscles_path, notice: 'ゲストユーザーとしてログインしました。'
  end


  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false)
        flash[:error] = '退会済みです。'
        redirect_to new_user_session_path
      end
    else
      flash[:error] = '必須項目を入力してください。'
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @muscles = current_user.muscles.includes([:part])
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def edit
    @user = current_user
    @guest_user = User.guest
  end

  def update
    user = current_user
    if user.update(user_params)
      flash[:notice] = '登録情報を更新しました'
      redirect_to user_path(user)
    else
      render 'edit'
    end
  end

  def unsubscribe
    @user = current_user
    @guest_user = User.guest
  end

  def withdraw
    user = current_user
    user.update(is_deleted: true)
    reset_session
    flash[:notice] = 'ありがとうございました'
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<a class="icon"><i class="fas fa-user-circle"></i><%= link_to "フォロー#{ user.followings.count }",follows_user_path(user.id) %></a>
<a class="icon"><i class="fas fa-users"></i><%= link_to "フォロワー#{ user.followers.count }", followers_user_path(user.id) %></a>
<div class="row justify-content-center">
<% if !user.belongs_to_current_user?(current_user) %>
	<% if user.followed_by?(current_user) %>
		<a class="icon"><%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, remote: true, :class => "btn btn-danger" %></a>
	<% else %>
		<a class="icon"><%= link_to "フォローする", user_relationships_path(user.id), method: :post, remote: true, :class => "btn btn-primary" %></a>
	<% end %>
<% end %>
</div>

app/views/users/edit.html.erb
<div class="row justify-content-center">
	<h1>登録情報編集</h1>
	<%= render "users/shared/error_messages", resource: @user %>
</div>
<% if @user != @guest_user %>
<div class="row justify-content-center">
	<%= form_for (@user) do |f| %>
		<div class='form-group row'>
			<div class='col-lg-4'>
				<h5><%= f.label :name, "名前" %></h5>
			</div>
			<div class='col-lg-8'>
				<span style='display: inline-block;'>
					<%= f.text_field :name  %>
				</span>
			</div>
		</div>
		<div class='form-group row'>
			<div class='col-lg-4'>
				<h5><%= f.label :email, "Eメール" %></h5>
			</div>
			<div class='col-lg-8'>
				<%= f.text_field :email, autofocus: true, autocomplete: 'email', class: 'form-control' %>
			</div>
		</div>
		<div class='form-group row'>
			<div class='col-lg-4'>
				<div class="user-image">
				<%= attachment_image_tag @user, :image, fallback: "no_image.jpg", id: "img_prev", style: "height: 200px; width:200px;" %><br>
				</div>
			</div>
			<div class='col-lg-8'>
				<%= f.attachment_field :image %>
			</div>
		</div>
		<div class="form-group-btn">
			<%= f.submit '編集内容を保存する', class:'btn btn-primary' %>
			<div class="col-lg-4">
				<%= link_to '退会する', unsubscribe_user_path(@user), class:'btn btn-danger'  %>
			</div>
		</div>
	<% end %>
</div>
<% end %>
<div class="row justify-content-center mt-5">
	<% if @user == @guest_user %>
		<h1>ゲストユーザーは編集できません。</h1>
	<% end %>
</div>
<script type="text/javascript" src="application.js"></script>

app/views/users/followers.html.erb
<div class="row justify-content-center">
	<% @users.each do |user| %>
	  <table class="table table-striped table-bordered">
	      <tr>
		      <td class="follow-show">
		        <%= link_to "#{ user.name }のページへいく", user_path(user), class: "btn btn-light" %>
		      </td>
		      <td class="follow-show">
		         <%= link_to "マイページへ", user_path(user.id), class: "btn btn-light" %>
		      </td>
				</tr>
		</table>
	<% end %>
</div>

app/views/users/follows.html.erb
<div class="row justify-content-center">
	<% @users.each do |user| %>
  	<table class="table table-striped table-bordered">
      <tr>
	      <td>
	        <%= link_to "#{ user.name }のページへいく", user_path(user), class: "btn btn-light" %>
	      </td>
	      <td>
	        <%= link_to "マイページへ", user_path(user.id), class: "btn btn-light" %>
	      </td>
			</tr>
		</table>
	<% end %>
</div>

app/views/users/show.html.erb
<h2 class="row justify-content-center mt-3">マイページ</h2>
<div class="row justify-content-center">
	<div class="col-11 border">
		<div class="row border-bottom">
			<div class="col-md-6 text-center">
				<%= attachment_image_tag @user, :image, fallback: "no_image.jpg", size:'100x100', class: "img-circle" %>
			</div>
			<div class="col-md-6 mt-5 text-center">
				<h4><%= @user.name %></h4>
			</div>
		</div>
		<div class="row border-bottom">
			<% if @user.belongs_to_current_user?(current_user) %>			
					<div class="col-md-6 text-center mt-3">
						<a class="icon"><%= link_to "編集する", edit_user_path(@user) %><i class="fas fa-user-edit"></i></a>
					</div>
					<div class="col-md-6 text-center mt-3">
						<a class="icon"><%= link_to "パスワード変更", edit_user_registration_path(@user) %><i class="fas fa-user-cog"></i></a>
					</div>
			<% end %>
		</div>
		<div class="row justify-content-center my-3 ">
			<div class="user_<%= @user.id %>">
   			<%= render 'users/follow', user: @user %>
    	</div>
    </div>
  </div>
</div>
<% if @user.belongs_to_current_user?(current_user) %>
<%= month_calendar events: @muscles do |date, muscles| %>
	<%= date.day %>
  <% muscles.each do |muscle| %>
  	<%= link_to "#{ muscle.part.name }",muscle_path(muscle.id) %>
  <% end %>
<% end %>
<% end %>

app/views/users/unsubscribe.html.erb
<% if @user != @guest_user %>
  <div class="col-lg-10 offset-lg-1 space">
    <div class="row space">
      <h2>本当に退会しますか？</h2>
    </div>

    <div class="row space">
      <h4>退会すると、登録情報や
        <br>これまでの投稿履歴が閲覧できなくなります。
        <br>退会する場合は「退会する」をクリックしてください。
      </h4>
    </div>

    <div class="row space">
      <%= link_to "退会しない",user_path(current_user),class: "btn btn-primary" %>
      <%= link_to "退会する", withdraw_user_path(current_user), method: :patch, "data-confirm" => "本当に退会しますか？", class: "btn btn-danger" %>
    </div>
  </div>
<% end %>
<div class="row justify-content-center mt-5">
	<% if @user == @guest_user %>
		<h1>ゲストユーザーは退会できません。</h1>
	<% end %>
</div>