config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/top' => 'homes#top'
  get 'homes/about' => 'homes#about'
  get 'homes/profile' => 'homes#profile'
  devise_for :admins,
             controllers: {
               sessions: 'admins/sessions',
               passwords: 'admins/passwords',
               registrations: 'admins/registrations'
             }
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations'
             }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admins/sessions#guest_admin'
  end
  namespace :admins do
    resources :contacts, only: %i[index edit update destroy]
  end
  get 'users/search' => 'searches#search'
  resources :contacts, only: %i[new create]
  resources :parts, only: %i[new create]
  resources :bigs, only: %i[show destroy]
  resources :muscles, only: %i[show update edit index destroy create] do
    resources :muscle_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
    resource :tags, only: [:index]
    get :following, on: :member
    get :workout, on: :member
  end
  get '/muscle/hashtag/:name', to: 'muscles#hashtag'

  resources :users, only: %i[show update edit] do
    resource :relationships, only: %i[create destroy]
    get :follows, on: :member
    get :followers, on: :member
    patch :withdraw, on: :member
    get :unsubscribe, on: :member
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/admins/contacts_controller.rb
class Admins::ContactsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @contacts = Contact.page(params[:page]).order(created_at: :desc).per(16)
    @users = User.all
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    contact = Contact.find(params[:id]) # contact_mailer.rbの引数を指定
    contact.update(contact_params)
    user = contact.user
    ContactMailer.send_when_admin_reply(user, contact).deliver_now # 確認メールを送信
    redirect_to admins_contacts_path
  end

  def destroy
    contact = Contact.find(params[:id])
    contact.destroy
    redirect_to admins_contacts_path
  end

  private

  def contact_params
    params.require(:contact).permit(:title, :body, :reply)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
    if @contact.save
      redirect_to muscles_path
      flash[:notice] = 'お問い合わせを送信しました。'
    else
      redirect_to request.referer
      flash[:notice] = '全て入力して下さい'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:title, :body, :reply)
  end
end

app/helpers/admins/contacts_helper.rb
module Admins::ContactsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/admins/contacts/edit.html.erb
<div class="row  justify-content-center mt-5">
    <h2>お問い合わせ詳細</h2>
</div>
<div class="row justify-content-center mt-3 ml-3 mr-3">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>ユーザー名</th>
        <th>問い合わせタイトル</th>
        <th>受信日</th>
      </tr>
    </thead>
    <tbody>
      <td><%= @contact.user.name %></td>
      <td><%= @contact.title %></td>
      <td><%= l @contact.created_at, format: :long  %></td>
    </tbody>
  </table>
</div>
<div class="row  justify-content-center mt-5">
  <h3>問い合わせ内容</h3>
</div>
<div class="row  justify-content-center mt-3">
  <%= @contact.body %>
</div>
<%= form_for @contact, url: admins_contact_path do |f| %>
  <div class="row  justify-content-center mt-5">
    <h3>返信</h3>
  </div>
  <div class="row  justify-content-center">
    <%= f.text_field :reply, class:"form-control", placeholder: "返信内容" %>
  </div>
<div class="row  justify-content-center">
    <%= f.submit "送信", class: "btn btn-primary w-25 mt-3" %>
</div>
<% end %>
</div>

app/views/admins/contacts/index.html.erb
<div class="row  justify-content-center">
    <h2>問い合わせ一覧</h2>
</div>
<div class="row justify-content-center ml-3 mr-3">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>ユーザー名</th>
        <th>問い合わせタイトル</th>
        <th>受信日</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <% user.contacts.each do |contact| %>
          <tr>
            <td><%= contact.user.name %></td>
            <td><%= contact.title %></td>
            <td><%= l contact.created_at, format: :middle %></td>
            <td><%= link_to "返信", edit_admins_contact_path(contact) %></td>
            <td><%= link_to "削除", admins_contact_path(contact), method: :delete %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>