config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/top' => 'homes#top'
  get 'homes/about' => 'homes#about'
  get 'homes/profile' => 'homes#profile'
  devise_for :admins,
             controllers: {
               sessions: 'admins/sessions',
               passwords: 'admins/passwords',
               registrations: 'admins/registrations'
             }
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations'
             }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admins/sessions#guest_admin'
  end
  namespace :admins do
    resources :contacts, only: %i[index edit update destroy]
  end
  get 'users/search' => 'searches#search'
  resources :contacts, only: %i[new create]
  resources :parts, only: %i[new create]
  resources :bigs, only: %i[show destroy]
  resources :muscles, only: %i[show update edit index destroy create] do
    resources :muscle_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
    resource :tags, only: [:index]
    get :following, on: :member
    get :workout, on: :member
  end
  get '/muscle/hashtag/:name', to: 'muscles#hashtag'

  resources :users, only: %i[show update edit] do
    resource :relationships, only: %i[create destroy]
    get :follows, on: :member
    get :followers, on: :member
    patch :withdraw, on: :member
    get :unsubscribe, on: :member
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/muscle.rb
class Muscle < ApplicationRecord
  belongs_to :user
  belongs_to :part
  has_many :favorites, dependent: :destroy
  has_many :muscle_comments, dependent: :destroy
  has_many :muscle_tags, dependent: :destroy
  has_many :tags, through: :muscle_tags
  validates :weight, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :set_count, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :memo, presence: true
  validates :rep, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def belongs_to_current_user?(current_user)
    user == current_user
  end
  
  scope :perfect_work_tag_match, ->(work_tag) { where(work_tag:work_tag) }
  scope :backward_work_tag_match, ->(work_tag) { where('work_tag LIKE ?', "%#{work_tag}") }
  scope :forward_work_tag_match, ->(work_tag) { where('work_tag LIKE ?', "#{work_tag}%") }
  scope :partical_work_tag_match, ->(work_tag) { where('work_tag LIKE ?', "%#{work_tag}%") }
  after_create do
    # 1.controller側でcreateしたmuscleを取得
    muscle = Muscle.find_by(id: id)
    # 2.正規表現を用いて、muscleのwork_tag内から『#○○○』の文字列を検出
    tags = work_tag.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    # 3.mapメソッドでtags配列の要素一つ一つを取り出して、先頭の#を取り除いてDBへ保存する
    tags.uniq.map do |t|
      tag = Tag.find_or_create_by(tag_name: t.downcase.delete('#'))
      muscle.tags << tag
    end
  end
end

app/controllers/muscles_controller.rb
class MusclesController < ApplicationController
  before_action :authenticate_user!
  def show
    @muscle = Muscle.find(params[:id])
    @user = @muscle.user
    @muscle_comment = MuscleComment.new
  end

  def hashtag
    @tag = Tag.find_by(tag_name: params[:name])
    @muscles = @tag.muscles.page(params[:page]).per(10)
  end

  def index
    @user = current_user
    @muscles = Muscle.all.includes([:user, :part]).page(params[:page]).per(10)
  end

  def following
    user = User.find(current_user.id)
    @users = user.followings
    @muscles = Muscle.where(user_id: @users).order('created_at DESC').page(params[:page]).per(10)
  end

  def edit
    @muscle = Muscle.find(params[:id])
    if @muscle.user == current_user
      @user = current_user
      @part = @muscle.part
    else
      redirect_to muscles_path
    end
  end

  def update
    muscle = Muscle.find(params[:id])
    if muscle.update(muscle_params)
      flash[:notice] = '投稿を編集しました'
      redirect_to muscle_path(muscle.id)
    else
      redirect_to request.referer
      flash[:notice] = '全て記入してから投稿して下さい'
    end
  end

  def workout
    @muscle = Muscle.new
    @user = current_user
    @part = Part.find(params[:id])
  end

  def create
    @muscle = Muscle.new(muscle_params)
    @muscle.user_id = current_user.id
    if @muscle.save
      redirect_to muscle_path(@muscle)
      flash[:notice] = '筋トレよく頑張った🔥'
    else
      redirect_to request.referer
      flash[:notice] = '全て記入してから投稿して下さい'
    end
  end

  def destroy
    muscle = Muscle.find(params[:id])
    muscle.destroy
    redirect_to muscles_path
  end

  private

  def muscle_params
    params.require(:muscle).permit(:memo, :set_count, :weight, :rep, :part_id, :work_tag, :start_time)
  end
end

app/helpers/muscles_helper.rb
module MusclesHelper
  def render_with_hashtags(work_tag)
    sanitize work_tag.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/) { |word| link_to word, "/muscle/hashtag/#{word.delete('#')}" }
    # gsubでハッシュタグ(/[#＃])と＃についてる文字(\w\p{Han}ぁ-ヶｦ-ﾟー]+/)をlink_to wordでリンクにして、sanitizeでhtml化している。
    # sanitizeを使う理由はXSS対策である。.html_safeだとrubocopにも怒られる
  end
end

app/views/muscles/_comment.html.erb
<% muscle.muscle_comments.includes([:user]).each do |muscle_comment| %>
<div class="row">
  <div class="col-md-6 mt-5 text-center">
    <div class="row justify-content-center mt-5">
        <div class="col-4 mt-3 text-center">
          <%= attachment_image_tag muscle.user, :image, fallback: "no_image.jpg", size:'50x50', class: "img-circle pull-left profile-thumb" %>
        </div>
        <div class="col-4 mt-3 text-center">
          <%= link_to "#{ muscle_comment.user.name }",user_path(muscle_comment.user.id) %>
        </div>
        <div class="col-4 mt-3 text-center">
         <span class="comment-date"><%= l muscle_comment.created_at, format: :middle %></span>
        </div>
    </div>
  </div>
</div>
<div class="row ml-3">
  <div class="co-l0 mt-5">
    <%= muscle_comment.comment %>
  </div>
  <div class="col-2 mt-5">
    <% if muscle_comment.belongs_to_current_user?(current_user) %>
    <i class="fas fa-trash"></i><%= link_to "削除", muscle_muscle_comment_path(muscle_comment.muscle, muscle_comment), method: :delete, remote: true %>
    <% end %>
  </div>
</div>
<% end %>

app/views/muscles/_favpage.html.erb
<% if muscle.favorited_by?(current_user) %>
  <%= link_to muscle_favorites_path(muscle), method: :delete, remote: true do %>
  <i class="fas fa-thumbs-up"></i>
  <%= muscle.favorites.count %>
  <% end %>
<% else %>
  <%= link_to muscle_favorites_path(muscle), method: :post, remote: true do  %>
  <i class="far fa-thumbs-up"></i>
  <%= muscle.favorites.count %>
  <% end %>
<% end %>

app/views/muscles/_muscle.html.erb
<% muscles.each do |muscle| %>
	<div class="row justify-content-center">
		<!-- work_out本体 -->
		<div class="col-8  my-3 border">
			<!-- ヘッダー -->
			<div class="row justify-content-center border-bottom">
				<div class="col-6 pl-0 align-self-center text-left">
					<td>
					<%= link_to user_path(muscle.user_id) do %>
					<%= attachment_image_tag muscle.user, :image, fallback: "no_image.jpg", size:'70x70', class: "rounded-circle" %>
					<% end %>
					</td>
					<td>
					<%= link_to muscle.user.name, muscle_path(muscle.id) %>
					</td>
				</div>
				<div class="col-4 pl-0 align-self-center text-right">
					<td>
					<%= l muscle.created_at, format: :short %>
					</td>
				</div>
			</div>

			<div class="row">
				<!-- 左半分 -->
				<div class="col-md-6 text-center pt-5">
				<div class="row">
						<!-- タグ -->
						<div class="col mt-2">
							<i class="fas fa-tags"></i><%= render_with_hashtags(muscle.work_tag) %>
						</div>
					</div>
				</div>
				<!-- 右半分 -->
				<div class="col-md-6">
					<div class="row my-2 border-bottom">
						<!-- 筋トレの簡易情報について -->
						<div class="col-10">
							<td>
								種目名:<%= muscle.part.name %>
							</td>
						</div>
						<div class="col-10">
							<td>
								重量:<%= muscle.weight %>kg
							</td>
						</div>
						<div class="col-10">
							<td>
								レップ数:<%= muscle.rep %>rep
							</td>
						</div>
						<div class="col-10">
							<td>
								セット数:<%= muscle.set_count%>set
							</td>
						</div>
					</div>
					<div class="row mt-2">
						<!-- コメント -->
						<div class="col">
							<i class="fas fa-comment"></i>
							<td>
								<%= muscle.muscle_comments.count %>件コメント
							</td>
						</div>
						<!-- いいね -->
						<div class="col">
							<div id="favorite-2">
								<td>
									<p class="muscles_<%= muscle.id %>">
			            <%= render 'muscles/favpage', muscle: muscle %>
			        	</p>
			          </td>
							</div>
						</div>
					</div>
				</div>
				<div class="row my-3 mx-auto">
					<!-- 詳細ページへのボタン -->
					<div class="col-12 text-center">
						<td>
							<%= link_to "詳細", muscle_path(muscle.id) %>
						</td>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>
	<div class="row justify-content-center">
 	<%= paginate muscles %>
 	</div>

app/views/muscles/edit.html.erb
<div class="row justify-content-center">
	<h1>投稿編集</h1>
</div>
<%= form_with model: @muscle, local: true do |f| %>
<div class="row justify-content-center">
</div>
<div class="row justify-content-center">
	<div class="field">
		<%= f.label :weight, "重量" %>
		<%= f.text_field :weight, placeholder: "100kg"%>
	</div>
</div>
<div class="row justify-content-center">
	<div class="field">
	    <%= f.label :rep, "回数" %>
	    <%= f.text_field :rep, placeholder: "10rep"%>
	</div>
</div>
<div class="row justify-content-center">
	<div class="field-set">
	    <%= f.label :set_count, "セット数" %>
	    <%= f.text_field :set_count, placeholder: "３セット"%>
	</div>
</div>
<div class="row justify-content-center">
	<div class="field">
	   <%= f.label :memo, "メモ" %>
	   <%= f.text_field :memo %>
	</div>
</div>
<div class="row justify-content-center">
	<div class="field">
	   <%= f.label :work_tag, "タグ" %>
	   <%= f.text_field :work_tag, placeholder: "#を先頭につけて下さい　例：#今日の筋トレ" %>
	</div>
</div>
<div class="row justify-content-center">
	<%= f.hidden_field :part_id, :value => @part.id %>
	<%= f.submit "編集内容を保存する", class: "btn btn-primary w-25" %>
</div>
<% end %>

app/views/muscles/following.html.erb
<div class="row  justify-content-center">
	<h1>FRIEND WORKOUT</h1>
</div>
<%= render 'muscles/muscle', muscles: @muscles %>

app/views/muscles/hashtag.html.erb
<div class="row  justify-content-center">
	<h1>#<%= @tag.tag_name %>タグの一覧</h1>
</div>
<%= render 'muscles/muscle', muscles: @muscles %>

app/views/muscles/index.html.erb
<div class="row  justify-content-center">
	<%= form_tag(users_search_path, method: :get) do %>
    <%= text_field_tag 'search[content]' %>
   	<%= select_tag 'search[model]', options_for_select({ "ユーザー" => "user", "タグ" => "muscle" }) %>
		 <%= select_tag 'search[how]', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"  }) %>
    <%= submit_tag '検索', class: "btn btn-primary" %>
  <% end %>
</div>
<div class="row  justify-content-center">
		<h1>ALL WORKOUT</h1>
</div>
	<%= render 'muscles/muscle', muscles: @muscles %>

app/views/muscles/new.html.erb
<div class="container">
	<%= render "users/shared/error_messages", resource: @muscle %>
	<%= form_with model: @muscle, local: true do |f| %>
	<div class="row justify-content-center">
			<div class="field">
				<%= f.label :genre, "部位" %>
				<%= f.collection_select :part_id, @user.parts, :id, :name, :include_blank => "選択してください" %>
			</div>
	</div>
	<div class="row justify-content-center">
			<div class="field">
				<%= f.label :genre, "種目" %>
				<%= f.text_field :genre, placeholder: "懸垂"  %>
			</div>
	</div>
	<div class="row justify-content-center">
			<div class="field">
				<%= f.label :weight, "重量" %>
				<%= f.text_field :weight, placeholder: "100kg"%>
			</div>
	</div>
	<div class="row justify-content-center">
			<div class="field">
			    <%= f.label :rep, "回数" %>
			    <%= f.text_field :rep, placeholder: "10rep"%>
			</div>
	</div>
	<div class="row justify-content-center">
			<div class="field-set">
			    <%= f.label :set_count, "セット数" %>
			    <%= f.text_field :set_count, placeholder: "３セット"%>
			</div>
	</div>
	<div class="row justify-content-center">
			<div class="field">
			    <%= f.label :memo, "メモ" %>
			    <%= f.text_field :memo%>
			</div>
	</div>
	<div class="row justify-content-center">
			<%= f.submit "投稿", class: "btn btn-primary w-25" %>
	</div>
	<% end %>
</div>

app/views/muscles/show.html.erb
<div class="row">
    <div class="col-auto ml-1 mt-2 page-title">
      <h3>投稿詳細</h3>
    </div>
</div>
<div class="row  justify-content-center">
  <div class="card">
    <div class="text-right">
    </div>
    <div class="card-header">
       <%= attachment_image_tag @user, :image, fallback: "no_image.jpg", size:'100x100', class: "img-circle" %>
      <h4 class="card-name"><%= link_to "#{ @user.name }", user_path(@user) %>の投稿</h4>
    </div>
    <div class="card-body">
        <h5 style="font-weight: bold;"><i class="fas fa-calendar-week"></i> 日付</h5>
        <%= l @muscle.created_at, format: :long %>
      <hr>
        <h5 style="font-weight: bold;"><i class="fas fa-dumbbell"></i>部位</h5>
         <%= @muscle.part.big.name%>
      <hr>
        <h5 style="font-weight: bold;"><i class="fas fa-running"></i> 種目</h5>
        <%= @muscle.part.name %>
      <hr>
        <h5 style="font-weight: bold;"><i class="fas fa-dumbbell"></i>重量</h5>
          <%= @muscle.weight %>kg
      <hr>
        <h5 style="font-weight: bold;"><i class="fas fa-dumbbell"></i>レップ数</h5>
          <%= @muscle.rep %>rep
      <hr>
        <h5 style="font-weight: bold;"><i class="fas fa-history"></i>セット数</h5>
        <%= @muscle.set_count%>set
      <hr>
        <h5 style="font-weight: bold;"><i class="far fa-file"></i>メモ</h5>
        <%= @muscle.memo%>
      <hr>
        <h5 style="font-weight: bold;"><i class="fas fa-thumbs-up"></i>いいね</h5>
        <h5 class="muscles_<%= @muscle.id %>">
          <%= render 'muscles/favpage', muscle: @muscle %>
        </h5>
      <hr>
        <h5 style="font-weight: bold;"><i class="fas fa-pen"></i></i>コメント数</h5>
        <%= @muscle.muscle_comments.count %>件コメント
      <hr>
        <h5 style="font-weight: bold;"><i class="fas fa-tag"></i> タグ</h5>
        <%= render_with_hashtags(@muscle.work_tag) %>
        <hr>
        <% if @muscle.belongs_to_current_user?(current_user) %>
          <%= link_to "編集する", edit_muscle_path(@muscle), class: "btn btn-success" %>
          <%= link_to "削除する",muscle_path(@muscle), method: :delete, "data-confirm" => "本当に消しますか？",  class: "btn btn-dark"%>
          <%= link_to "ALL WORKOUTへ", muscles_path, class: "btn btn-danger" %>
        <% end %>
    </div>
  </div>
</div>
<div class="row  justify-content-center">
  <table class="table">
    <tr>
    <td class="muscle_<%= @muscle.id %>">
        <%= render 'muscles/comment', muscle: @muscle %>
    </td>
    </tr>
  </table>
    <%= form_with(model: [@muscle, @muscle_comment]) do |f| %>
      <div class="row">
        <div class="col-sm-12">
          <%= f.text_field :comment, class: "form-control",placeholder: "コメントをここに" %>
        </div>
      </div>
      <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
    <% end %>
</div>

app/views/muscles/workout.html.erb
<div class="row justify-content-center">
	<h1><%= @part.name %>の投稿</h1>
	<h2 class="btn-gradient-radius-part mt-3">・タグは#をつけて下さい</h2>
	<h2 class="btn-gradient-radius-part mt-3">・タグは必須入力ではありません</h2>
</div>
<%= render "users/shared/error_messages", resource: @muscle %>
<%= form_with model: @muscle, local: true do |f| %>
<div class="row justify-content-center">
	<div class="field">
		<%= f.label :start_time, "日付" %>
		<%= f.date_field :start_time %>
	</div>
</div>
<div class="row justify-content-center">
	<div class="field">
		<%= f.label :weight, "重量" %>
		<%= f.text_field :weight, placeholder: "100"%>
	</div>
</div>
<div class="row justify-content-center">
	<div class="field">
    <%= f.label :rep, "回数" %>
    <%= f.text_field :rep, placeholder: "10"%>
	</div>
</div>
<div class="row justify-content-center">
	<div class="field-set">
    <%= f.label :set_count, "セット数" %>
    <%= f.text_field :set_count, placeholder: "3"%>
	</div>
</div>
<div class="row justify-content-center">
	<div class="field">
	  <%= f.label :memo, "メモ" %>
	  <%= f.text_field :memo %>
	</div>
</div>
<div class="row justify-content-center">
	<div class="field">
	  <%= f.label :work_tag, "タグ" %>
	  <%= f.text_field :work_tag, placeholder: "#を先頭につけて下さい　例：#今日の筋トレ" %>
	</div>
</div>
<div class="row justify-content-center">
		<%= f.hidden_field :part_id, :value => @part.id %>
		<%= f.submit "投稿", class: "btn btn-danger w-25" %>
</div>
<% end %>